[package]
name = "risc0-zkvm-verify"
version = "0.9.0"
edition = "2021"
description = "RISC Zero zero-knowledge proof system core crate"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
anyhow = "1.0"
array-init = "2.0"
bytemuck = { version = "1.9", features = ["derive"] }
paste = "1.0"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_core = "0.6"
sha2 = { version = "0.10", features = ["compress"] }
serde = { version = "1.0", features = ["derive"] }
risc0-zkp-core = { version = "0.9", path = "../../../../zkp/rust/core" }
risc0-zkp-hal = { version = "0.9", path = "../hal", optional = true }
risc0-zkvm-serde = { version = "0.9", path = "../serde" }

[dev-dependencies]
bencher = "0.1.5"
env_logger = "0.9"
log = "0.4"
test-log = "0.2"

[[bench]]
name = "verify"
harness = false

[features]
default = ["prove", "verify"]
prove = ["dep:risc0-zkp-hal"]
verify = []
