[package]
name = "json-example"
version = "0.1.0"
edition = "2021"

[dependencies]
json-core = { path = "core" }
json-methods = { path = "methods" }
risc0-zkvm = { path = "../../risc0/zkvm" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]
